/**
 * FlightLog
 */
export interface FlightLog {
    modes: string;
    reg: string;
    squawk: string;
    country: string;
    gjdq: string;
    mbzl: string;
    typeCode: string;
    typeDesc: string;
    zbxh: string;
    mbbh: string;
    mbmc: string;
    mbxz: number;
    gsd: number;
    hh: string;
    hqsd: string;
    sd: number;
    bbh: string;
    jd: number;
    wd: number;
    ydfx: number;
    sbsj: number;
    wzsj: number;
    pzdw: string;
    qmbmc: string;
    mmpy: string;
    ddd: string;
    ph: string;
    silType: string;
    seenPos: number;
    seen: number;
    sda: string;
    rssi: number;
    rc: string;
    nicBaro: string;
    nicC: string;
    nicA: string;
    nic: string;
    tisbVersion: string;
    adsrVersion: string;
    airCompany: string;
    originCode: string;
    targetCode: string;
    origin: string;
    target: string;
    takeOffTime: number;
    landTime: number;
    day: string;
}
